/**
 * Commit classification.
 * Signals evaluated highest-to-lowest priority — first match wins.
 */

import type {
  Ai,
  Classification,
  ClassificationResult,
  CommitPayload,
  Human,
} from "./types.js";

// ── Level 1: GitHub Bot type — login → agent ────────────────────────────────

const BOT_LOGIN_MAP: Record<string, string> = {
  "copilot-swe-agent": "copilot",
  "devin-ai-integration": "devin",
  cursoragent: "cursor",
  "dependabot[bot]": "dependabot",
  "renovate[bot]": "renovate",
};

// ── Level 2: Author email — exact or pattern ────────────────────────────────

const EMAIL_EXACT: Record<string, string> = {
  "dependabot@github.com": "dependabot",
  "renovate@renovateapp.com": "renovate",
};

// ── Level 3: Known AI logins GitHub misreports as User ──────────────────────

const KNOWN_AI_LOGINS: Record<string, string> = {
  copilot: "copilot",
  "gemini-code-assist": "gemini",
};

// ── Level 4: Co-Authored-By email → agent ───────────────────────────────────

const CO_AUTHOR_EMAIL_MAP: Record<string, string> = {
  "noreply@anthropic.com": "claude",
  "cursoragent@cursor.com": "cursor",
  "noreply@aider.chat": "aider",
};

const CO_AUTHOR_RE = /Co-Authored-By:\s*(.+?)\s*<(.+?)>/gi;

// ── Helpers ─────────────────────────────────────────────────────────────────

const human = (): Human => ({ kind: "human" });
const ai = (agent: string | null): Ai => ({ kind: "ai", agent });
const result = (
  classification: Classification,
  coAuthors: string[] = [],
): ClassificationResult => ({ classification, coAuthors });

function classifyAuthorEmail(
  email: string,
  name: string | null,
): string | null {
  if (email in EMAIL_EXACT) return EMAIL_EXACT[email];
  if (email.includes("[bot]") && email.endsWith("@users.noreply.github.com"))
    return "other-bot";
  if (email === "noreply@github.com" && (name ?? "").toLowerCase() === "github")
    return "github-actions";
  if (email.endsWith("@cursor.com")) return "cursor";
  return null;
}

function parseCoAuthors(
  message: string,
): { aiClassification: Classification | null; coAuthors: string[] } {
  const coAuthors: string[] = [];
  let aiClassification: Classification | null = null;

  for (const m of message.matchAll(CO_AUTHOR_RE)) {
    const name = m[1].trim();
    const email = m[2].trim();
    coAuthors.push(`${name} <${email}>`);
    if (aiClassification === null) {
      const agent = CO_AUTHOR_EMAIL_MAP[email];
      if (agent) aiClassification = ai(agent);
    }
  }

  return { aiClassification, coAuthors };
}

function classifyMessage(message: string): Classification | null {
  if (message.includes("Generated with Claude Code")) return ai("claude");
  if (message.includes("Generated with Cursor")) return ai("cursor");
  if (message.includes("Generated by GitHub Copilot")) return ai("copilot");
  for (const line of message.split("\n")) {
    if (/^aider:/i.test(line)) return ai("aider");
  }
  if (message.includes("AI-generated")) return ai(null);
  return null;
}

// ── Classifier ──────────────────────────────────────────────────────────────

export function classifyCommit(commit: CommitPayload): ClassificationResult {
  // Level 1: GitHub Bot type
  if (commit.authorType === "Bot") {
    const agent = BOT_LOGIN_MAP[commit.authorLogin ?? ""] ?? "other-bot";
    return result(ai(agent));
  }

  // Level 2: Author email
  if (commit.authorEmail) {
    const agent = classifyAuthorEmail(commit.authorEmail, commit.authorName);
    if (agent) return result(ai(agent));
  }

  // Level 3: Known AI logins
  if (commit.authorLogin && commit.authorLogin in KNOWN_AI_LOGINS) {
    return result(ai(KNOWN_AI_LOGINS[commit.authorLogin]));
  }

  // Level 4: Co-Authored-By trailers
  const { aiClassification, coAuthors } = parseCoAuthors(
    commit.message ?? "",
  );
  if (aiClassification !== null) return result(aiClassification, coAuthors);
  if (coAuthors.length > 0) return result(human(), coAuthors);

  // Level 5: Message markers
  const msgCls = classifyMessage(commit.message ?? "");
  if (msgCls !== null) return result(msgCls);

  // Level 6: Author name suffix
  if (commit.authorName && /\(aider\)/i.test(commit.authorName)) {
    return result(ai(null));
  }

  return result(human());
}
