import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { classifyCommit } from "../../src/classify/commit-classifier.js";
import type {
  Classification,
  CommitPayload,
} from "../../src/classify/types.js";

// ── Fixture loading ─────────────────────────────────────────────────────────

type FixtureCase = {
  description: string;
  signals: Record<string, unknown>;
  expected_classification: { kind: string; agent?: string | null };
  expected_co_authors?: string[];
};

const FIXTURES: FixtureCase[] = JSON.parse(
  readFileSync(
    resolve(__dirname, "../fixtures/commit-cases.json"),
    "utf-8",
  ),
);

const DEFAULTS: CommitPayload = {
  message: "fix: a bug",
  authorLogin: "alice",
  authorType: "User",
  authorEmail: "alice@example.com",
  authorName: "Alice",
  committerEmail: "alice@example.com",
  committerName: "Alice",
};

// Map snake_case fixture keys to camelCase payload keys
const KEY_MAP: Record<string, keyof CommitPayload> = {
  message: "message",
  author_login: "authorLogin",
  author_type: "authorType",
  author_email: "authorEmail",
  author_name: "authorName",
  committer_email: "committerEmail",
  committer_name: "committerName",
};

function buildPayload(signals: Record<string, unknown>): CommitPayload {
  const merged = { ...DEFAULTS };
  for (const [key, value] of Object.entries(signals)) {
    const mapped = KEY_MAP[key];
    if (mapped) (merged as Record<string, unknown>)[mapped] = value;
  }
  return merged;
}

function parseClassification(d: {
  kind: string;
  agent?: string | null;
}): Classification {
  if (d.kind === "human") return { kind: "human" };
  return { kind: "ai", agent: d.agent ?? null };
}

// ── Data-driven tests ───────────────────────────────────────────────────────

describe("classifyCommit (fixtures)", () => {
  for (const fixture of FIXTURES) {
    it(fixture.description, () => {
      const payload = buildPayload(fixture.signals);
      const expected = parseClassification(fixture.expected_classification);
      const expectedCoAuthors = fixture.expected_co_authors ?? [];

      const result = classifyCommit(payload);

      expect(result.classification).toEqual(expected);
      expect(result.coAuthors).toEqual(expectedCoAuthors);
    });
  }
});

// ── Priority and edge cases ─────────────────────────────────────────────────

describe("classifyCommit (edge cases)", () => {
  it("null author fields do not throw", () => {
    const result = classifyCommit({
      message: "fix: something",
      authorLogin: null,
      authorType: null,
      authorEmail: null,
      authorName: null,
      committerEmail: null,
      committerName: null,
    });
    expect(result.classification).toEqual({ kind: "human" });
  });

  it("Bot type wins over Co-Authored-By", () => {
    const result = classifyCommit({
      ...DEFAULTS,
      authorLogin: "dependabot[bot]",
      authorType: "Bot",
      message:
        "bump lodash\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
    });
    expect(result.classification).toEqual({ kind: "ai", agent: "dependabot" });
  });

  it("email wins over message marker", () => {
    const result = classifyCommit({
      ...DEFAULTS,
      authorEmail: "cursoragent@cursor.com",
      message: "fix: thing\n\nGenerated by GitHub Copilot",
    });
    expect(result.classification).toEqual({ kind: "ai", agent: "cursor" });
  });

  it("Co-Authored-By wins over message marker", () => {
    const result = classifyCommit({
      ...DEFAULTS,
      message:
        "fix\n\nCo-Authored-By: Cursor <cursoragent@cursor.com>\n\nGenerated by GitHub Copilot",
    });
    expect(result.classification).toEqual({ kind: "ai", agent: "cursor" });
  });
});
